In [2]:
x = [[1,2,3],[4,5,6],[7,8,9]]
ind = []
for i in range(len(x)):
  for j in range(len(x)):
    if i==j:
      ind.append([i,j])
    if i+j==2:
      ind.append([i,j])
print(ind)
i = 0
j = -1
while i < len(ind)//2:
  ind_i1, ind_j1 = ind[i]
  ind_i2, ind_j2 = ind[j]
  x[ind_i1][ind_j1],x[ind_i2][ind_j2] = x[ind_i2][ind_j2],x[ind_i1][ind_j1]
  i+=1
  j-=1
print(x)

[[0, 0], [0, 2], [1, 1], [1, 1], [2, 0], [2, 2]]
[[9, 2, 7], [4, 5, 6], [3, 8, 1]]


# Add two numbers

Adding two number using lambda function


In [68]:
# Define a lambda function to add two numbers
add_numbers = lambda x, y: x + y

# Take input from the user
num1 = 10
num2 = 5

# Call the lambda function to add the two numbers
result = add_numbers(num1, num2)

# Print the result
print("The sum of", num1, "and", num2, "is", result)

The sum of 10 and 5 is 15


Python program to add two numbers with recursive function

In [4]:
# Define a recursive function to add two numbers
def add_numbers_recursive(x, y):
	if y == 0:
		return x
	else:
		return add_numbers_recursive(x + 1, y - 1)

# Take input from the user
num1 = 10
num2 = 20

# Call the recursive function to add the two numbers
result = add_numbers_recursive(num1, num2)

# Print the result
print("The sum of", num1, "and", num2, "is", result)

The sum of 10 and 20 is 30


# Find Maximum of two numbers in Python


Maximum of two numbers Using lambda function


In [5]:
# python code to find maximum of two numbers

a=2;b=4
maximum = lambda a,b:a if a > b else b
print(f'{maximum(a,b)} is a maximum number')

4 is a maximum number


Maximum of two numbers Using list comprehension


In [6]:
a=2;b=4
x=[a if a>b else b]
print("maximum number is:",x)

maximum number is: [4]


Maximum of two numbers Using sort() method


In [7]:
# Python program to find the
# maximum of two numbers
a = 2
b = 4
x=[a,b]
x.sort()
print(x[-1])

4


# Python Program to Find the Factorial of a Number


Find the Factorial of a Number Using Recursive approach


In [8]:
# Python 3 program to find
# factorial of given number
def factorial(n):

	# single line to find factorial
	return 1 if (n==1 or n==0) else n * factorial(n - 1)

# Driver Code
num = 6
print("Factorial of",num,"is",factorial(num))

Factorial of 6 is 720


Find the Factorial of a Number Using Iterative approach


In [9]:
# Python 3 program to find
# factorial of given number
def factorial(n):
	if n < 0:
		return 0
	elif n == 0 or n == 1:
		return 1
	else:
		fact = 1
		while(n > 1):
			fact *= n
			n -= 1
		return fact

# Driver Code
num = 5
print("Factorial of",num,"is",
factorial(num))

Factorial of 5 is 120


In [10]:
# Python 3 program to find
# factorial of given number

# Function to find factorial of given number
def factorial(n):

	res = 1

	for i in range(2, n+1):
		res *= i
	return res
# Driver Code
num = 5
print("Factorial of", num, "is",
factorial(num))

Factorial of 5 is 120


Find the Factorial of a Number Using using In-built function


In [11]:
# Python 3 program to find
# factorial of given number
import math

def factorial(n):
	return(math.factorial(n))


# Driver Code
num = 5
print("Factorial of", num, "is",
	factorial(num))

Factorial of 5 is 120


# Python Program for Prime Number


In [80]:
def prime(starting_range, ending_range):
  lst=[]
  flag=False                #Declaring flag variable
  for i in range(starting_range, ending_range):#elements range between starting and ending range
    for j in range(2,i):
      if(i%j==0):     #checking if number is divisible or not
        flag=True        #if number is divisible, then flag variable will become 1
        break
      else:
        flag=False
    if(flag==False):    #if flag variable is 0, then element will append in list
      lst.append(i)
  return lst

# Driver program
starting_range = 2
ending_range = 7
lst = prime(starting_range, ending_range)
if len(lst) == 0:
    print("There are no prime numbers in this range")
else:
    print("The prime numbers in this range are: ", lst)

The prime numbers in this range are:  [2, 3, 5]


Python Program to Check Prime Number


In [13]:
num = 157
# If given number is greater than 1
if num > 1:
  # Iterate from 2 to n / 2
  for i in range(2, num//2+1):
    # If num is divisible by any number between
    # 2 and n / 2, it is not prime
    if (num % i) == 0:
      print(num, "is not a prime number")
      break
  else:
    print(num, "is a prime number")
else:
  print(num, "is not a prime number")

157 is a prime number


# Python Program for n-th Fibonacci number

Python Program for n-th Fibonacci number Using recursion


In [84]:
# Function for nth Fibonacci number

def Fibonacci(n):
	if n<= 0:
		print("Incorrect input")
	# First Fibonacci number is 0
	elif n == 1:
		return 0
	# Second Fibonacci number is 1
	elif n == 2:
		return 1
	else:
		return Fibonacci(n-1)+Fibonacci(n-2)

# Driver Program

print(Fibonacci(0))


Incorrect input
None


In [108]:
def Fib(n):
  res = [0,1,1]
  if n < 4:
    return res[n-1]
  else:
    for i in range(2,n):
      res.append(res[i]+res[i-1])
  return res
n = int(input())
res = Fib(n)
if n in res:
  print("true")
else:
  print("false")

13
true


# Program to print ASCII Value of a character


In [15]:
c = 'g'
print("The ASCII value of '" + c + "' is", ord(c))

The ASCII value of 'g' is 103


Cumulative Sum

In [16]:
lists = [10, 20, 30, 40, 50]

for i in range(1,len(lists)):
  lists[i] = lists[i-1] + lists[i]
print(lists)

[10, 30, 60, 100, 150]


# Python Program to Add Two Matrices


Add Two Matrices Using for loop


In [17]:
# Program to add two matrices using nested loop

X = [[1,2,3],
	[4 ,5,6],
	[7 ,8,9]]

Y = [[9,8,7],
	[6,5,4],
	[3,2,1]]


result = [[0,0,0],
		[0,0,0],
		[0,0,0]]

# iterate through rows
for i in range(len(X)):
# iterate through columns
	for j in range(len(X[0])):
		result[i][j] = X[i][j] + Y[i][j]

for r in result:
	print(r)


[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


Add Two Matrices Using List comprehension

In [18]:
# Program to add two matrices
# using list comprehension

X = [[1,2,3],
	[4 ,5,6],
	[7 ,8,9]]

Y = [[9,8,7],
	[6,5,4],
	[3,2,1]]

result = [[X[i][j] + Y[i][j] for j in range
(len(X[0]))] for i in range(len(X))]

for r in result:
	print(r)


[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


Add Two Matrices Using Numpy

In [19]:
# Program to add two matrices
# using numpy

import numpy as np

X = [[1,2,3],
	[4 ,5,6],
	[7 ,8,9]]

Y = [[9,8,7],
	[6,5,4],
	[3,2,1]]

result = np.array(X) + np.array(Y)

print(result.tolist())


[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


# Python program to multiply two matrices


Using Simple Nested Loops

In [61]:
# take a 3x3 matrix
A = [[12, 7, 3],
	[4, 5, 6],
	[7, 8, 9]]

# take a 3x4 matrix
B = [[5, 8, 1, 2],
	[6, 7, 3, 0],
	[4, 5, 9, 1]]

result = [[0, 0, 0, 0],
		[0, 0, 0, 0],
		[0, 0, 0, 0]]

# iterating by row of A
for i in range(len(A)):

	# iterating by column by B
	for j in range(len(B[0])):

		# iterating by rows of B
		for k in range(len(B)):
			result[i][j] += A[i][k] * B[k][j]

for r in result:
	print(r)


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


Program to multiply two matrices using list comprehension

In [62]:
# take a 3x3 matrix
A = [[12, 7, 3],
	[4, 5, 6],
	[7, 8, 9]]

# take a 3x4 matrix
B = [[5, 8, 1, 2],
	[6, 7, 3, 0],
	[4, 5, 9, 1]]

# result will be 3x4
result = [[sum(a * b for a, b in zip(A_row, B_col))
						for B_col in zip(*B)]
								for A_row in A]

for r in result:
	print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


Matrix Multiplication (Vectorized implementation).

In [65]:
import numpy as np
# take a 3x3 matrix
A = [[12, 7, 3],
	[4, 5, 6],
	[7, 8, 9]]

# take a 3x4 matrix
B = [[5, 8, 1, 2],
	[6, 7, 3, 0],
	[4, 5, 9, 1]]

result = np.dot(A,B)

for r in result:
	print(r)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


Adding and Subtracting Matrices in Python


In [79]:
A = [[1,2],[3,4]]
B = [[4,5],[6,7]]

add = [[0,0],[0,0]]
sub = np.zeros(4).reshape(2,2)
for i in range(len(A)):
  for j in range(len(A[i])):
    add[i][j] = A[i][j] + B[i][j]
    sub[i][j] = A[i][j] - B[i][j]
print(add,sub)

[[5, 7], [9, 11]] [[-3. -3.]
 [-3. -3.]]


# Python | Matrix Product


In [67]:
# initializing list
test_list = [[1, 4, 5], [7, 3], [4], [46, 7, 3]]

# printing original list
print("The original list : " + str(test_list))

x = []
for i in test_list:
	x.extend(i)
print(x)
res = 1
for j in x:
	res *= j


# print result
print("The total element product in lists is : " + str(res))

The original list : [[1, 4, 5], [7, 3], [4], [46, 7, 3]]
[1, 4, 5, 7, 3, 4, 46, 7, 3]
The total element product in lists is : 1622880


Transpose of a matrix using numpy

In [81]:
import numpy
matrix=[[1,2,3],[4,5,6]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))

[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


# Dictionary

Python – Extract Unique values dictionary values


In [7]:
test_dict = {'gfg' : [5, 6, 7, 8],
            'is' : [10, 11, 7, 5],
            'best' : [6, 12, 10, 8],
            'for' : [1, 2, 5]}

# printing original dictionary
print("The original dictionary is : " + str(test_dict))

# Extract Unique values dictionary values
x=[]
for i in test_dict.keys():
    x.extend(test_dict[i])
x=list(set(x))
x.sort()
# printing result
print("The unique values list is : " + str(x))

The original dictionary is : {'gfg': [5, 6, 7, 8], 'is': [10, 11, 7, 5], 'best': [6, 12, 10, 8], 'for': [1, 2, 5]}
The unique values list is : [1, 2, 5, 6, 7, 8, 10, 11, 12]


# Numpy questions

In [20]:
import numpy as np

In [21]:
print(np.__version__)
np.show_config()

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [22]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [24]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [25]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [26]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [27]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [29]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.75524154 0.13939138 0.69447697]
  [0.12270816 0.59128865 0.91517936]
  [0.771564   0.12049184 0.75303816]]

 [[0.52445648 0.42779603 0.75489382]
  [0.64168712 0.9042983  0.26749174]
  [0.06164489 0.54106931 0.53412653]]

 [[0.86935071 0.3938755  0.07739678]
  [0.50637436 0.30930517 0.34121374]
  [0.64323715 0.53428655 0.3392879 ]]]


In [31]:
Z = np.random.random((10,10))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

[[0.08178953 0.65548053 0.66200394 0.47972098 0.36293421 0.02223252
  0.8185775  0.2220571  0.08227107 0.53451549]
 [0.40898408 0.16320837 0.95043492 0.29238852 0.74598422 0.0579516
  0.65626188 0.95303444 0.42409526 0.68758737]
 [0.63606417 0.06317519 0.78760377 0.10723052 0.15279695 0.515227
  0.17849455 0.9487469  0.20377559 0.46204368]
 [0.11014554 0.60424283 0.44038611 0.18083257 0.91645919 0.4085292
  0.22249692 0.40789408 0.41181842 0.82643102]
 [0.0624076  0.4512405  0.83310909 0.78562625 0.60618685 0.25005934
  0.05152697 0.08118621 0.4043512  0.44908414]
 [0.70341192 0.63331639 0.61434229 0.78238274 0.83645928 0.58120348
  0.6073906  0.9860051  0.39065791 0.33642081]
 [0.71371969 0.55811764 0.3463721  0.21727328 0.69962165 0.29018413
  0.277526   0.88464896 0.85759581 0.79313421]
 [0.2499455  0.75072831 0.62739733 0.66423093 0.42910346 0.89203608
  0.69435382 0.18605141 0.951977   0.15624301]
 [0.74671947 0.54649008 0.91187637 0.34224519 0.21054338 0.60689528
  0.12678694 0.6

In [32]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5252222537769452


In [33]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [34]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal,A,B)

False [0 1 0 1 0] [0 1 1 0 1]


In [35]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

In [36]:
import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.27607732 0.26243786 0.60965909 0.10631473 0.34033105
  0.57795083 0.49128831 0.51228794 0.33344236]
 [0.27607732 0.         0.49928453 0.59714942 0.27720099 0.58674923
  0.60960199 0.65404926 0.78145894 0.52150843]
 [0.26243786 0.49928453 0.         0.84677189 0.35441596 0.39170346
  0.79911021 0.63140542 0.3068271  0.47989023]
 [0.60965909 0.59714942 0.84677189 0.         0.50388552 0.58696726
  0.0963106  0.39013273 0.98078061 0.43119055]
 [0.10631473 0.27720099 0.35441596 0.50388552 0.         0.30996214
  0.4718833  0.4080776  0.56760176 0.25784859]
 [0.34033105 0.58674923 0.39170346 0.58696726 0.30996214 0.
  0.50939975 0.26075215 0.40332325 0.15607165]
 [0.57795083 0.60960199 0.79911021 0.0963106  0.4718833  0.50939975
  0.         0.29702169 0.90916441 0.35608964]
 [0.49128831 0.65404926 0.63140542 0.39013273 0.4080776  0.26075215
  0.29702169 0.         0.65824077 0.1596365 ]
 [0.51228794 0.78145894 0.3068271  0.98078061 0.56760176 0.40332325
  0.90916441 0.65824

In [38]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [41]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [43]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [47]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)


In [48]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. How to swap two rows of an array? (★★★)

In [58]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)



[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [60]:
x = float(2.8)
print(type(x))

<class 'float'>
